### ISSUE TITLE
Missing catch error for non Cordova platform

### ISSUE THREAD

**Issue by dbertolini** [ionicthemes/ionic-firebase-authentication#1]
In the file "auth.service.ts" is missing the "err" response to reject for non Cordova platforms.

Trying this app with "ionic serve -l" I realized tht when the user closes the pop up window at Google Login, it crash with a message error.

![ionic-error-message](https://user-images.githubusercontent.com/14815454/44482756-a65b5300-a61f-11e8-9533-7f01db2f4bbc.png)

_**Example for doGoogleLogin function:**_

**### Before:**

doGoogleLogin(){
     return new Promise<FirebaseUserModel>((resolve, reject) => {
       if (this.platform.is('cordova')) {
         this.googlePlus.login({
           'scopes': '', // optional, space-separated list of scopes, If not included or empty, defaults to `profile` and `email`.
           'webClientId': environment.googleWebClientId, // optional clientId of your Web application from Credentials settings of your project - On Android, this MUST be included to get an idToken. On iOS, it is not required.
           'offline': true
         }).then((response) => {
           const googleCredential = firebase.auth.GoogleAuthProvider.credential(response.idToken);
           firebase.auth().signInWithCredential(googleCredential)
           .then((user) => {
             resolve();
           });
         },(err) => {
           reject(err);
         });
       }
       else{
         this.afAuth.auth
         .signInWithPopup(new firebase.auth.GoogleAuthProvider())
         .then((user) => {
            resolve();
         });
       }
     })
   }

**### After:**

doGoogleLogin(){
     return new Promise<FirebaseUserModel>((resolve, reject) => {
       if (this.platform.is('cordova')) {
         this.googlePlus.login({
           'scopes': '', // optional, space-separated list of scopes, If not included or empty, defaults to `profile` and `email`.
           'webClientId': environment.googleWebClientId, // optional clientId of your Web application from Credentials settings of your project - On Android, this MUST be included to get an idToken. On iOS, it is not required.
           'offline': true
         }).then((response) => {
           const googleCredential = firebase.auth.GoogleAuthProvider.credential(response.idToken);
           firebase.auth().signInWithCredential(googleCredential)
           .then((user) => {
             resolve();
           });
         },(err) => {
           reject(err);
         });
       }
       else{
         this.afAuth.auth
         .signInWithPopup(new firebase.auth.GoogleAuthProvider())
         .then((user) => {
            resolve();
         }**,(err) => {
          reject(err);
        }**);
       }
     })
   }

**Comment by djabif** [comment]
thanks for submitting the PR ;)
