### ISSUE TITLE
Facebook Login not possible

### ISSUE THREAD

**Issue by cgaeking** [ionicthemes/ionic-firebase-authentication#8]
When trying to login via facebook, this screen appears always:
![image](https://user-images.githubusercontent.com/7023716/106595465-e85c8300-6553-11eb-9667-3c11d6be9ffe.png)

**Comment by djabif** [comment]
Facebook requires https for facebook login. However, if you are developing your app you can set your Facebook App in developer mode and you will be able to perform login from localhost. You can read more [here](https://developers.facebook.com/blog/post/2018/06/08/enforce-https-facebook-login/).
